### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by xyproto** [tardisgo/tardisgo#38]
Hi,

Tardisgo is now available as an unofficial Arch Linux package:
https://aur.archlinux.org/packages/tardisgo/

But, which version number should I use? Is it version 0.1? I searched through the files and documentation, but could not find it.

Best regards,
   Alexander F Rødseth

**Comment by elliott5** [comment]
Wonderful that Tardisgo is available in this way Alexander, thank you.
I'm not sure how to answer you about a version number.
I'd say it has not hit version 0.1 yet, because I'm changing it every day at the moment.
What would your advice be?

Elliott

**Comment by xyproto** [comment]
One possibility is just going for version 0.1 and just keep it at that until there are enough changes that you want people to upgrade, then use version 0.2 etc. It is also possible to tag the version with "git tag", like for instance the gin project, and many others, has done: https://github.com/gin-gonic/gin

This way, packages for various distros can choose to depend either on the version tag or a specific commit when downloading the sources. As long as a git tag is available for each release, providing source tarballs is not needed anymore, and has largely gone out of fashion.

Just tagging the latest commit as "v0.1" should do the trick, but it's entirely up to you, of course. Some projects just add another digit to e at each release.. https://en.wikipedia.org/wiki/Metafont#History

Alexander

**Comment by elliott5** [comment]
Thanks Alexander, the project is now v0.1 !


Elliott
