### ISSUE TITLE
JS benchmarks

### ISSUE THREAD

**Issue by tomlarkworthy** [tardisgo/tardisgo#47]
Hi, I have also been benchmarking Haxe. FYI, you can shave 25% off by running the JS through the Closure compiler.

**Comment by elliott5** [comment]
Great news Tom, thank you for looking at the project.
Which option are you using on the Closure compiler, and are you adding anything to the Haxe to achieve that?

**Comment by elliott5** [comment]
I've run the benchmarks after running the Closure compiler (using the standard options), and there are good savings as you say, so I'll highlight those in the "Benchmark" results section.

**Comment by elliott5** [comment]
Closure/JS benchmark figures added.
Should I do anything else?

**Comment by elliott5** [comment]
Closed as issue out of date.
